### ISSUE TITLE
Release pretrained teacher model

### ISSUE THREAD

**Issue by liuhao-lh** [JiaxinZhuang/DisCo#1]
Thanks for releasing this amazing work.

Would you release the pre-trained teacher models and some training logs?

**Comment by JiaxinZhuang** [comment]
Sure, we would release the pre-trained teacher models soon, which are used in our paper. Because of some reasons, logs can't be released.

**Comment by liuhao-lh** [comment]
> Sure, we would release the pre-trained teacher models soon, which are used in our paper. Because of some reasons, logs can't be released.

Thanks for your reply！Looking forward to your update.

**Comment by JiaxinZhuang** [comment]
Hi~
We have release ResNet152(800eps), ResNet101(200eps), ResNet50 (200eps) teacher models.  Other teacher models can be found on their official github.

**Comment by JiaxinZhuang** [comment]
> > Sure, we would release the pre-trained teacher models soon, which are used in our paper. Because of some reasons, logs can't be released.
> 
> Thanks for your reply！Looking forward to your update.


Hi~
We have released ResNet152(800eps), ResNet101(200eps), ResNet50 (200eps) teacher models. Other teacher models can be found on their official github.

**Comment by liuhao-lh** [comment]
> > > Sure, we would release the pre-trained teacher models soon, which are used in our paper. Because of some reasons, logs can't be released.
> > 
> > 
> > Thanks for your reply！Looking forward to your update.
> 
> Hi~
> We have released ResNet152(800eps), ResNet101(200eps), ResNet50 (200eps) teacher models. Other teacher models can be found on their official github.

Thanks!
